CREATE TABLE IF NOT EXISTS mpa (mpa_id INTEGER PRIMARY KEY, name VARCHAR(10) NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS genres (genre_id INTEGER PRIMARY KEY, name VARCHAR(100) NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS friendship_statuses (status_id INTEGER PRIMARY KEY, name VARCHAR(50) NOT NULL UNIQUE);

CREATE TABLE IF NOT EXISTS users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    login VARCHAR(100) NOT NULL,
    name VARCHAR(255),
    birthday DATE NOT NULL
    );

CREATE TABLE IF NOT EXISTS films (
    film_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(200),
    release_date DATE NOT NULL,
    duration INTEGER NOT NULL,
    mpa_id INTEGER NOT NULL,

    CONSTRAINT fk_films_mpa
    FOREIGN KEY (mpa_id)
    REFERENCES mpa (mpa_id)
    );

CREATE TABLE IF NOT EXISTS film_genres (
    film_id BIGINT NOT NULL,
    genre_id INTEGER NOT NULL,
    CONSTRAINT pk_film_genres
    PRIMARY KEY (film_id, genre_id),

    CONSTRAINT fk_film_genres_film
    FOREIGN KEY (film_id)
    REFERENCES films (film_id)
    ON DELETE CASCADE,

    CONSTRAINT fk_film_genres_genre
    FOREIGN KEY (genre_id)
    REFERENCES genres (genre_id)
    );

CREATE TABLE IF NOT EXISTS film_likes (
    film_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_film_likes
    PRIMARY KEY (film_id, user_id),

    CONSTRAINT fk_film_likes_film
    FOREIGN KEY (film_id)
    REFERENCES films (film_id)
    ON DELETE CASCADE,

    CONSTRAINT fk_film_likes_user
    FOREIGN KEY (user_id)
    REFERENCES users (user_id)
    ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS friendships (
    user_id BIGINT NOT NULL,
    friend_id BIGINT NOT NULL,
    status_id INTEGER NOT NULL,

    CONSTRAINT pk_friendships
    PRIMARY KEY (user_id, friend_id),

    CONSTRAINT fk_friendships_user
    FOREIGN KEY (user_id)
    REFERENCES users (user_id)
    ON DELETE CASCADE,

    CONSTRAINT fk_friendships_friend
    FOREIGN KEY (friend_id)
    REFERENCES users (user_id)
    ON DELETE CASCADE,

    CONSTRAINT fk_friendships_status
    FOREIGN KEY (status_id)
    REFERENCES friendship_statuses (status_id),

    CONSTRAINT chk_friendship_not_self
    CHECK (user_id <> friend_id)
    );

CREATE INDEX IF NOT EXISTS idx_friendships_friend_id
    ON friendships (friend_id);

CREATE INDEX IF NOT EXISTS idx_film_genres_genre_id
    ON film_genres (genre_id);

CREATE TABLE IF NOT EXISTS events (
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    timestamp BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    event_type VARCHAR(10) NOT NULL,
    operation VARCHAR(10) NOT NULL,
    entity_id BIGINT NOT NULL,

    CONSTRAINT fk_events_user
    FOREIGN KEY (user_id)
    REFERENCES users (user_id)
    ON DELETE CASCADE,

    CONSTRAINT chk_event_type
    CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND')),

    CONSTRAINT chk_operation
    CHECK (operation IN ('REMOVE', 'ADD', 'UPDATE'))
    );

CREATE INDEX IF NOT EXISTS idx_events_user_time
    ON events (user_id, timestamp DESC);
